[BUGFIX] fail when specifying a configfile path
- PB: path.resolve is called whith the specified path and also with
undefined as second parameter. This leads to an error:
TypeError: Path must be a string. Received undefined
- FIX: force the second argument as an empty string